version: '3.8'
services:
  movieworld-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movieworld-react-app
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
